---
apiVersion: v1
kind: Service
metadata:
  name: gyro
  labels:
    app: gyro
spec:
  type: LoadBalancer
  ports:
    - port: 4000
      name: web
  selector:
    app: gyro
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gyro
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gyro
    spec:
      containers:
        - name: gyro
          image: gyro:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
              name: web
          env:
            - name: DATABASE_HOST
              value: postgres.default.svc.cluster.local
          command: ["mix", "phoenix.server"]
