---
apiVersion: v1
kind: Service
metadata:
  name: gyro
spec:
  type: LoadBalancer
  selector:
    app: gyro
  ports:
    - port: 4000
      targetPort: web
      name: web

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gyro
  labels:
    app: gyro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gyro
  template:
    metadata:
      labels:
        app: gyro
    spec:
      containers:
        - name: gyro
          image: gyro:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
              name: web
          env:
            - name: PORT
              value: "4000"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP