apiVersion: v1
kind: Service
metadata:
  name: gyro
spec:
  selector:
    app: gyro
  ports:
    - name: web
      port: 4000
      targetPort: web

---

apiVersion: v1
kind: Service
metadata:
  name: gyro-headless
spec:
  clusterIP: None
  selector:
    app: gyro
  ports:
    - name: epmd
      port: 4369

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gyro
  labels:
    app: gyro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gyro
  template:
    metadata:
      labels:
        app: gyro
    spec:
      containers:
        - name: gyro
          image: gyro:0.2.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
              name: web
          env:
            - name: PORT
              value: "4000"
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: K8S_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP