version: "2"
services:
  postgres:
    image: "postgres:9.6"
    environment:
      POSTGRES_DB: gyro_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  postgres_test:
    image: "postgres:9.6"
    environment:
      POSTGRES_DB: gyro_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  node:
    image: "node:7-alpine"
    working_dir: "/gyro"
    command: "./node_modules/.bin/brunch watch"
    volumes:
      - ./:/gyro

  # the main image, this is the application
  web:
    build:
      context: .
      dockerfile: ./deployments/Dockerfile
    image: "gyro:dev"
    command: "mix phoenix.server"
    ports:
      - "4000:4000"
    volumes:
      - ./:/gyro
    links:
      - postgres

  test:
    build:
      context: .
      dockerfile: ./deployments/Dockerfile
    image: "gyro:dev"
    command: "mix test"
    volumes:
      - ./:/gyro
    links:
      - postgres_test:postgres

  build-node:
    image: "node:7-alpine"
    working_dir: "/gyro"
    command: "./node_modules/.bin/brunch b -p"
    volumes:
      - ./:/gyro

  build:
    build:
      context: .
      dockerfile: ./deployments/Dockerfile
    image: "gyro:dev"
    environment:
      MIX_ENV: prod
    command: bash -c "mix deps.get && mix phoenix.digest && mix release --env=prod"
    volumes:
      - ./:/gyro

  release:
    build:
      context: .
      dockerfile: ./deployments/Dockerfile.release
      args:
        VERSION: 0.0.1
    image: "gyro:0.0.1"
    environment:
      MIX_ENV: "prod"
      MIX_VERSION: "0.0.1"
    working_dir: /gyro
    volumes:
      - ./:/gyro
