version: "2"
services:
  postgres:
    image: "postgres:9.4"
    environment:
      POSTGRES_USER: postgres

  # the main image, this is the application
  elixir:
    build:
      context: .
      dockerfile: ./deployments/Dockerfile
    image: "gyro:dev"
    command: "mix phoenix.server"
    ports:
      - "4000:4000"
    volumes:
      - ./:/gyro
    depends_on:
      - postgres

  node:
    image: "node:7-alpine"
    working_dir: "/gyro"
    command: "./node_modules/.bin/brunch watch"
    volumes:
      - ./:/gyro

  build:
    build:
      context: .
      dockerfile: ./deployments/Dockerfile
    image: "gyro:dev"
    environment:
      MIX_ENV: prod
    command: bash -c "./node_modules/brunch/bin/brunch b -p && mix deps.get && mix phoenix.digest && mix release --env=prod"
    volumes:
      - ./:/gyro

  release:
    build:
      context: .
      dockerfile: ./deployments/Dockerfile.release
    image: "gyro:0.1"
    environment:
      MIX_ENV: "prod"
      MIX_VERSION: "0.0.1"
    working_dir: /gyro
    volumes:
      - ./:/gyro
