version: "3"
services:
  gyro: &gyro
    image: "gyro:dev"
    build:
      context: .
      dockerfile: ./deployments/Dockerfile
    command: mix setup
    volumes:
      - ./:/gyro

  # the main image, this is the application
  web:
    <<: *gyro
    command: "mix phx.server"
    ports:
      - "4000:4000"

  test:
    <<: *gyro
    command: "mix test"

  credo:
    <<: *gyro
    command: "mix credo"

  build:
    <<: *gyro
    environment:
      MIX_ENV: prod
    command: sh -c "mix deps.get --only prod && mix compile && mix phx.digest && mix distillery.release --env=prod"

  release:
    build:
      context: .
      dockerfile: ./deployments/Dockerfile.release
      args:
        VERSION: 0.2.0
    image: "gyro:0.2.0"
    environment:
      MIX_ENV: prod
      PORT: 4000
    working_dir: /gyro
    ports:
      - "4000:4000"
